pass1
tano-cloud/JavaScript-kadai-2-1 pull request #1
Opened 2020-07-23 10:16 UTC by tano-cloud

2020-07-24 11:15 UTC, myzktkyk requested changes
コードを書くのにかなり努力されたと思います。
よりよくできる点が何点かありますので、それぞれのコードについて指摘をさせていただきました。

## 全体的な指摘点
- 最初に入力値のチェックを行いましょう
  - 後の方に持っていくと意図しない入力値が処理に入ってきてしまい、異常終了してしまいます
- 全体的にかなり複雑になっている
  - 要件に対して過剰に複雑になっていると思います
  - もう少しシンプルになるように考えてみてください

2020-07-24 11:15 UTC, myzktkyk commented on index.html
> +                let fizzNum = Number(document.getElementById('idFizzNum').value);
このコードだとテキストボックスに入力がなかった場合 `0` が変数に格納され
後続の処理に続いてしまいます。

2020-07-24 11:15 UTC, myzktkyk commented on index.html
> +                    fizzNumAdd += fizzNum;
入力がない => `0` に変換された状態でここまでくると
`fizzNumAdd` が全く増えず、無限ループしてし、`out of memory` を起こします。

2020-07-24 11:15 UTC, myzktkyk commented on index.html
> +                        let selectFizz = re.test(buzzNum);
入力値のチェックをここまで後ろに引っ張る必要はないと思います。
もっと手前で行いましょう。

2020-07-24 11:15 UTC, myzktkyk commented on index.html
> +
全体的に特に意味のない空行が多いように思います。
削除するようにしてください。

2020-07-26 09:17 UTC, niganium commented
1点指摘点があります、修正したのち再提出をおねがいいたします
下記のスクリーンショットのように片方に整数が入っていると要件と違ったエラー文章が出力されてしまいます。
それと個人的にスタイルシートとスクリプトの記述を全てHTMLファイルに格納していることが気になりました。
特に挙動に影響はしませんが、可読性を下げ、記述ミスなどを発生させる要因となります。今後はなるべく全ての記述を１つのHTMLファイルに書くことは避けましょう。

![スクリーンショット 2020-07-26 18 06 09](https://user-images.githubusercontent.com/38875175/88475471-088b0400-cf6b-11ea-8ba1-d1826f858686.png)

![スクリーンショット 2020-07-26 18 06 38](https://user-images.githubusercontent.com/38875175/88475575-3b81c780-cf6c-11ea-8197-2a77e9957c42.png)

2020-07-31 04:29 UTC, merged